### ISSUE TITLE
How does one tryout for the supergroup?

### ISSUE THREAD

**Issue by defnotpaul** [yahreen/you-get-the-gist#1]
Is this more like a lottery or the olympics?

**Comment by yahreen** [comment]
- A minimum of 5 years software development experience which are Java/J2ee specific is required
- Self-motivated team player who excels in a collaborative environment
- Ecommerce experience is a must.
- Hands on experience with Agile methodologies.
- Strong sense of personal accountability; contributes beyond job role and responsibilities
- Excellent problem solving skills; meticulous & methodical
- Ability to learn and apply new technologies quickly and self-directed
- Proven ability to translate complex business requirements into simple software solutions
- Passionate about continuously improving organizational practices
- Thorough understanding of Object Oriented principles (Analysis and Design)
- Candidates must have a robust understanding of Java and an in-depth understanding of other Java technologies, including Servlets, Struts/Tiles, JSP, JDBC, JMS, - Spring
- Familiarity with front-end technologies &ndash; Object-Oriented Javascript, AJAX, XHTML, HTML, XML/DOM
- Full lifecycle development experience on large projects, creating distributed and scalable business systems.
- Experience with WebServices (REST, SOAP, XML-RPC, etc)
- Experience with relational databases and data access (JDBC/DAO/SQL) Oracle strongly preferred.
- Familiarity with ORM technologies (iBatis, Hibernate)
- Mentor and guide others who are still developing their skills
- Desired Qualifications include
- Familiarity with EAI patterns, queuing systems (e.g. MQ Series, JMS, etc.) and business process orchestration (e.g. BPEL), workflow automation systems, etc.
- Familiarity with Ruby
- Experience with test automation frameworks
- Experience in developing and driving SOA strategies within large enterprises and deploying SOA implementations to production a big plus

**Comment by defnotpaul** [comment]
<img width="184" alt="screen shot 2015-12-04 at 1 48 00 pm" src="https://cloud.githubusercontent.com/assets/515868/11602240/a78427b6-9a8d-11e5-8b25-6d52bdc670c4.png">

[u2013](http://www.fileformat.info/info/unicode/char/2013/index.htm)

**Comment by yahreen** [comment]
@eyeamera Updated

**Comment by defnotpaul** [comment]
LGTM
